apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: demo-app
        image: depwaswho/kubernetes-demo-app:1.0.0
        ports:
        - containerPort: 80